name: CI

on:
  push:
    branches-ignore: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Latest version can be found here: https://developer.android.com/studio#command-tools
      ANDROID_SDK_TOOLS: "4333796"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android SDK tools and platforms
      run: |
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
        sudo unzip -d $ANDROID_HOME android-sdk.zip > /dev/null 
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-15" > /dev/null
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null

    - name: Cache Gradle wrapper dist
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper/dists
        key: ${{ runner.os }}-gradle-dists-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Gradle depdendencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run build
      run: ./generateAndBuild.sh
