name: Publish on master push

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Latest version can be found here: https://developer.android.com/studio#command-tools
      ANDROID_SDK_TOOLS: "4333796"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Gradle wrapper dist
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper/dists
        key: ${{ runner.os }}-gradle-dists-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Gradle depdendencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run build
      run: ./generateAndPublish.sh
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
